version: 2
updates:
  # Main application
  - package-ecosystem: "npm"
    directory: "/"
    labels:
      - "dependabot :robot:"
    schedule:
      interval: "daily"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependabot :robot:"
    schedule:
      interval: "daily"
